export const CRYPTO_AI_PRIORITY_KEYWORDS = [
  "ai",
  "artificial intelligence",
  "ai agent",
  "ai agents",
  "decentralized ai",
  "machine learning",
  "gpu",
  "compute",
  "decentralized compute",
  "depin",
  "data network",
  "bittensor",
  "tao",
  "render",
  "rndr",
  "fetch.ai",
  "fet",
  "asi",
  "akash",
  "akt",
  "aioz",
  "near",
  "golem",
  "io.net",
  "grass",
  "ritual",
  "sahara ai",
] as const;

export const GENERAL_CRYPTO_KEYWORDS = [
  "bitcoin",
  "btc",
  "ethereum",
  "eth",
  "solana",
  "sol",
  "etf",
  "sec",
  "fed",
  "cpi",
  "interest rates",
  "liquidation",
  "whale",
  "binance",
  "coinbase",
  "blackrock",
  "microstrategy",
  "stablecoin",
  "usdt",
  "usdc",
  "hack",
  "exploit",
  "airdrop",
  "mainnet",
  "partnership",
  "listing",
] as const;

export const BREAKING_WORDS = [
  "breaking",
  "just in",
  "alert",
  "urgent",
  "developing",
  "exclusive",
];

export const MARKET_IMPACT_WORDS = [
  "surge",
  "crash",
  "rally",
  "dump",
  "pump",
  "record",
  "all-time high",
  "ath",
  "plunge",
  "soar",
  "tumble",
  "volatility",
];

export const REGULATION_WORDS = ["regulation", "etf", "fed", "cpi", "sec", "lawsuit", "ban"];

export const HACK_WORDS = ["hack", "exploit", "breach", "stolen", "drained", "security"];
